/** --------------------- */
/** Do not edit this file */
/** --------------------- */
import { urls } from "./data/urls.js";

// Fetch photos starting at the offset
export const getPhotos = (offset, limit = 9) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      // Validate
      if (offset + limit > urls.length) {
        reject();
      }

      resolve(urls.slice(offset, offset + limit));
    }, 200);
  });
};
