/** --------------------- */
/** Do not edit this file */
/** --------------------- */
import { user } from "./data/user.js";

// Fetch the current user
export const getUser = () => new Promise(resolve => resolve(user));
